VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ThisWorkbook"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
''Private Sub Worksheet_Activate()
'Private Sub Workbook_Open()
'
'Application.DisplayFullScreen = True
'Sheets("Main Sheet").Activate
'Range("A100").Activate
'Range("A63").Activate
'Range("A37").Activate
'Application.ScreenUpdating = True
'
'End Sub
